FROM --platform=linux/amd64 golang:1.23.3-bookworm as build

WORKDIR /blaxel/uvm-api

COPY ./uvm-api /blaxel/uvm-api

RUN set -xe; \
  go build \
  -v \
  -buildmode=pie \
  -ldflags "-linkmode external -extldflags -static-pie" \
  -tags netgo \
  -o uvm-api-binary . \
  ;

# Use an official Python runtime as a parent image
FROM --platform=linux/amd64 node:22-slim

COPY --from=build /blaxel/uvm-api/uvm-api-binary /usr/local/bin/uvm-api

