package api

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"slices"
	"strings"
	"testing"

	"github.com/blaxel-ai/sandbox-api/src/handler/process"
	"github.com/gin-gonic/gin"
	"gopkg.in/yaml.v3"
)

// These tests use real processes and HTTP handlers, not fabricated response
// structs. The checked-in OpenAPI is generated by `make reference` at repo root.
// The API promises required strings: unavailable output and completion time
// must be empty strings, never null.
func TestProcessHTTPResponsesMatchRequiredStringContract(t *testing.T) {
	originalLogDir := process.ProcessLogDir
	process.ProcessLogDir = t.TempDir()
	t.Cleanup(func() { process.ProcessLogDir = originalLogDir })
	gin.SetMode(gin.TestMode)
	router := SetupRouter(true, false)

	t.Run("running execution returns empty strings rather than null", func(t *testing.T) {
		// cat blocks on its open stdin rather than racing a sleep or fast exit.
		response := processContractRequest(t, router, http.MethodPost, "/process",
			`{"command":"cat","name":"contract-running","stdin":true,"waitForCompletion":false}`)
		t.Cleanup(func() {
			processContractRequest(t, router, http.MethodDelete, "/process/contract-running/kill", "")
		})
		body := decodeProcessContractResponse(t, response)
		if body["status"] != "running" {
			t.Fatalf("expected running process, got %v", body["status"])
		}
		assertEmptyProcessOutput(t, body)
		assertProcessStringContract(t, body)

		t.Run("running detail returns empty strings rather than null", func(t *testing.T) {
			response := processContractRequest(t, router, http.MethodGet, "/process/contract-running", "")
			body := decodeProcessContractResponse(t, response)
			assertEmptyProcessOutput(t, body)
			assertProcessStringContract(t, body)
		})

		t.Run("running listing returns empty completion rather than null", func(t *testing.T) {
			response := processContractRequest(t, router, http.MethodGet, "/process", "")
			var bodies []map[string]any
			if err := json.Unmarshal(response, &bodies); err != nil {
				t.Fatal(err)
			}
			for _, listed := range bodies {
				if listed["name"] == "contract-running" {
					if listed["status"] != "running" {
						t.Fatalf("expected running process in listing, got %v", listed["status"])
					}
					assertEmptyProcessOutput(t, listed)
					assertProcessStringContract(t, listed)
					return
				}
			}
			t.Fatal("running process missing from HTTP listing")
		})
	})

	t.Run("completed execution returns strings accepted by the contract", func(t *testing.T) {
		response := processContractRequest(t, router, http.MethodPost, "/process",
			`{"command":"sh -c 'printf stdout; printf stderr >&2'","name":"contract-completed","waitForCompletion":true}`)
		body := decodeProcessContractResponse(t, response)
		if body["status"] != "completed" {
			t.Fatalf("expected completed process, got %v", body["status"])
		}
		if body["stdout"] != "stdout" || body["stderr"] != "stderr" {
			t.Fatalf("expected command output stdout/stderr, got %v/%v", body["stdout"], body["stderr"])
		}
		if body["logs"] == nil || body["logs"] == "" || body["completedAt"] == nil || body["completedAt"] == "" {
			t.Fatal("completed execution must supply logs and a completion time")
		}
		assertProcessStringContract(t, body)

		t.Run("completed detail also matches the contract", func(t *testing.T) {
			response := processContractRequest(t, router, http.MethodGet, "/process/contract-completed", "")
			body := decodeProcessContractResponse(t, response)
			if body["status"] != "completed" {
				t.Fatalf("expected completed process in detail response, got %v", body["status"])
			}
			assertProcessStringContract(t, body)
		})
	})

	t.Run("completed execution with no output preserves empty strings", func(t *testing.T) {
		response := processContractRequest(t, router, http.MethodPost, "/process",
			`{"command":"true","name":"contract-empty","waitForCompletion":true}`)
		body := decodeProcessContractResponse(t, response)
		if body["status"] != "completed" || body["completedAt"] == "" {
			t.Fatal("expected completed process with a completion time")
		}
		for _, field := range []string{"logs", "stdout", "stderr"} {
			if body[field] != "" {
				t.Errorf("expected empty %s, got %v", field, body[field])
			}
		}
		assertProcessStringContract(t, body)
	})

	t.Run("streamed final response also supplies required strings", func(t *testing.T) {
		request := httptest.NewRequest(http.MethodPost, "/process", strings.NewReader(
			`{"command":"true","name":"contract-streamed","waitForCompletion":true}`))
		request.Header.Set("Content-Type", "application/json")
		request.Header.Set("Accept", "text/event-stream")
		response := httptest.NewRecorder()
		router.ServeHTTP(response, request)
		if response.Code != http.StatusOK {
			t.Fatalf("expected HTTP 200, got %d: %s", response.Code, response.Body.String())
		}
		if !strings.Contains(response.Header().Get("Content-Type"), "application/x-ndjson") {
			t.Fatalf("expected NDJSON stream, got %s", response.Header().Get("Content-Type"))
		}
		foundResult := false
		for _, line := range strings.Split(strings.TrimSpace(response.Body.String()), "\n") {
			var event struct {
				Type string `json:"type"`
				Data string `json:"data"`
			}
			if err := json.Unmarshal([]byte(line), &event); err != nil {
				t.Fatal(err)
			}
			if event.Type == "result" {
				foundResult = true
				body := decodeProcessContractResponse(t, []byte(event.Data))
				if body["status"] != "completed" {
					t.Fatalf("expected completed final response, got %v", body["status"])
				}
				assertProcessStringContract(t, body)
			}
		}
		if !foundResult {
			t.Fatal("stream did not include a final process response")
		}
	})
}

func processContractRequest(t *testing.T, router http.Handler, method, path, body string) []byte {
	t.Helper()
	request := httptest.NewRequest(method, path, strings.NewReader(body))
	request.Header.Set("Content-Type", "application/json")
	response := httptest.NewRecorder()
	router.ServeHTTP(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("%s %s: expected HTTP 200, got %d: %s", method, path, response.Code, response.Body.String())
	}
	return response.Body.Bytes()
}

func decodeProcessContractResponse(t *testing.T, response []byte) map[string]any {
	t.Helper()
	var body map[string]any
	if err := json.Unmarshal(response, &body); err != nil {
		t.Fatal(err)
	}
	return body
}

func assertEmptyProcessOutput(t *testing.T, body map[string]any) {
	t.Helper()
	for _, field := range []string{"logs", "stdout", "stderr", "completedAt"} {
		if value, exists := body[field]; !exists || value != "" {
			t.Errorf("expected %s to be present and an empty string, got %v (present=%v)", field, value, exists)
		}
	}
}

func assertProcessStringContract(t *testing.T, body map[string]any) {
	t.Helper()
	generated, err := os.ReadFile("../../docs/openapi.yml")
	if err != nil {
		t.Fatal(err)
	}
	var contract struct {
		Components struct {
			Schemas map[string]struct {
				Required   []string `yaml:"required"`
				Properties map[string]struct {
					Type     string `yaml:"type"`
					Nullable bool   `yaml:"nullable"`
				} `yaml:"properties"`
			} `yaml:"schemas"`
		} `yaml:"components"`
	}
	if err := yaml.Unmarshal(generated, &contract); err != nil {
		t.Fatal(err)
	}
	schema, exists := contract.Components.Schemas["ProcessResponse"]
	if !exists {
		t.Fatal("generated contract must define ProcessResponse")
	}

	for _, field := range []string{"logs", "stdout", "stderr", "completedAt"} {
		if !slices.Contains(schema.Required, field) {
			t.Errorf("generated ProcessResponse must require %s to be present", field)
		}
		property, exists := schema.Properties[field]
		if !exists || property.Type != "string" {
			t.Fatalf("generated ProcessResponse must describe %s as a string", field)
		}
		if property.Nullable {
			t.Errorf("generated ProcessResponse.%s must remain a nonnullable string", field)
		}
		value, exists := body[field]
		if !exists {
			t.Errorf("HTTP response must include %s", field)
			continue
		}
		if _, isString := value.(string); !isString {
			t.Errorf("HTTP response %s must be a string, got %T", field, value)
		}
	}
}
